version: "3.8"

services:
  backend:
    build: .
    container_name: pelakor-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgresqwe@localhost:5432/pelakor_db
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: pelakor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresqwe
      POSTGRES_DB: pelakor_db
    ports:
      - "5432:5432"
    volumes:
      - pelakor_data:/var/lib/postgresql/data

volumes:
  pelakor_data:
